# Vale is a linter / spellchecker
# https://vale.sh/docs

MinAlertLevel = warning
Packages = Google
StylesPath = .vale/styles
Vocab = SudokuSolver

[*]
BasedOnStyles = Vale, Google
Google.EmDash = NO

[*.md]
Google.FirstPerson = NO
Google.Headings = NO
; Google.WordList = NO
